### ISSUE TITLE
mx requires Mercurial and Git

### ISSUE THREAD

**Issue by christhalinger** [graalvm/mx#120]
When building in Jenkins we noticed this:

```
WARNING: no hg executable found
  File "/Users/cthalinger/mx/mx.py", line 14243, in <module>
    main()
  File "/Users/cthalinger/mx/mx.py", line 14121, in main
    _src_suitemodel.set_primary_dir(dirname(primarySuiteMxDir))
  File "/Users/cthalinger/mx/mx.py", line 5430, in set_primary_dir
    self._suiteRootDir = SuiteModel.siblings_dir(d)
  File "/Users/cthalinger/mx/mx.py", line 5400, in siblings_dir
    _, primary_vc_root = VC.get_vc_root(suite_dir)
  File "/Users/cthalinger/mx/mx.py", line 3235, in get_vc_root
    root = vcs.root(directory, abortOnError=False)
  File "/Users/cthalinger/mx/mx.py", line 3946, in root
    self.check_for_hg()
  File "/Users/cthalinger/mx/mx.py", line 3643, in check_for_hg
    abort(self.missing)
  File "/Users/cthalinger/mx/mx.py", line 9029, in abort
    traceback.print_stack()
no hg executable found
```

mx shouldn't require Mercurial when all your repositories are Git ones.

**Comment by christhalinger** [comment]
Oh, it needs all VCS tools now:

```
10:55:01 DEBUG: WARNING: No Git executable found. You must install Git in order to proceed!
10:55:01 DEBUG: No Git executable found. You must install Git in order to proceed!
```

**Comment by christhalinger** [comment]
It gets better... I'm installing Mercurial and Git now and:

```
11:35:19 DEBUG: cannot determine VC and root for /builddir/build/BUILD/java-1.8.0-twitter/graal-core
```

**Comment by smarr** [comment]
I think I saw something similar. If I remember correctly, there is somewhere code that tries to read the version, for instance, of the graal-jvmci-8 repo during building.

**Comment by dougxc** [comment]
@christhalinger , can you please test the following patch to see if it fixes the issue in your environment:

```
diff --git a/mx.py b/mx.py
index 19b7e78..864c068 100755
--- a/mx.py
+++ b/mx.py
@@ -3943,7 +3943,8 @@ class HgConfig(VC):
             abort('exists failed')

     def root(self, directory, abortOnError=True):
-        self.check_for_hg()
+        if not self.check_for_hg(abortOnError=abortOnError):
+            return None
         try:
             out = subprocess.check_output(['hg', 'root'], cwd=directory, stderr=subprocess.STDOUT)
             return out.strip()
@@ -4540,7 +4541,8 @@ class GitConfig(VC):
             return False

     def root(self, directory, abortOnError=True):
-        self.check_for_git()
+        if not self.check_for_git(abortOnError=abortOnError):
+            return None
         try:
             out = subprocess.check_output(['git', 'rev-parse', '--show-toplevel'], cwd=directory, stderr=subprocess.STDOUT)
             return out.strip()
@@ -5397,7 +5399,15 @@ class SuiteModel:
     @staticmethod
     def siblings_dir(suite_dir):
         if exists(suite_dir):
-            _, primary_vc_root = VC.get_vc_root(suite_dir)
+            _, primary_vc_root = VC.get_vc_root(suite_dir, abortOnError=False)
+            if not primary_vc_root:
+                suite_parent = dirname(suite_dir)
+                # Use the heuristic of a 'ci.hocon' file being
+                # at the root of a repo that contains multiple suites.
+                hocon = join(suite_parent, 'ci.hocon')
+                if exists(hocon):
+                    return dirname(suite_parent)
+                return suite_parent
         else:
             primary_vc_root = suite_dir
         return dirname(primary_vc_root)
@@ -14231,7 +14241,7 @@ def main():
         # no need to show the stack trace when the user presses CTRL-C
         abort(1)

-version = VersionSpec("5.46.0")
+version = VersionSpec("5.46.1")

 currentUmask = None
```

**Comment by christhalinger** [comment]
Sort of.  I used https://github.com/graalvm/truffle/releases/tag/graal-vm-0.16 and https://github.com/graalvm/truffle/releases/tag/graal-vm-0.16 and `eclipseinit` results in:

```
modified /Users/cthalinger/graalvm/mx/mxbuild/mx.mx/eclipse-project-settings
created /Users/cthalinger/Downloads/graal-core-graal-vm-0.16/workingsets.xml
Traceback (most recent call last):
  File "/Users/cthalinger/graalvm/mx/mx.py", line 14253, in <module>
    main()
  File "/Users/cthalinger/graalvm/mx/mx.py", line 14237, in main
    retcode = c(command_args)
  File "/Users/cthalinger/graalvm/mx/mx.py", line 10483, in eclipseinit_cli
    eclipseinit(None, args.buildProcessorJars, logToConsole=args.logToConsole, force=args.force)
  File "/Users/cthalinger/graalvm/mx/mx.py", line 10493, in eclipseinit
    fsckprojects([])
  File "/Users/cthalinger/graalvm/mx/mx.py", line 12108, in fsckprojects
    dirnames[:] = [d for d in dirnames if d not in [suite.vc.metadir(), suite.mxDir, 'lib', '.workspace', 'mx.imports']]
AttributeError: 'NoneType' object has no attribute 'metadir'
```

A `build` works fine.

**Comment by dougxc** [comment]
Ok, `eclipseinit` is fixed. Are there any other commands you care about that don't work without a VC dir?

**Comment by christhalinger** [comment]
No, everything else seems to work fine.  But I noticed this (which seems unrelated):

```
cthalinger@tw-mbp-cthalinger:~/Downloads/graal-core-graal-vm-0.16$ ~/graalvm/mx/mx junit
Traceback (most recent call last):
  File "/Users/cthalinger/graalvm/mx/mx.py", line 14253, in <module>
    main()
  File "/Users/cthalinger/graalvm/mx/mx.py", line 14237, in main
    retcode = c(command_args)
  File "/Users/cthalinger/graalvm/mx/mx.py", line 13578, in junit
    if not p.isJavaProject() or jdk.javaCompliance < p.javaCompliance:
UnboundLocalError: local variable 'jdk' referenced before assignment
```

**Comment by dougxc** [comment]
Ok, I'll fix that and the push changes.

**Comment by dougxc** [comment]
@christhalinger , please confirm https://github.com/graalvm/mx/commit/85b30ce56df7add4d41d32daac80d2bc6010f362 fixes the issue.

**Comment by christhalinger** [comment]
Locally it works, thanks.  I'll do a Jenkins build now...

**Comment by christhalinger** [comment]
The output is a little confusing but it works:

```
16:10:53 DEBUG: WARNING: no hg executable found
16:10:53 DEBUG: WARNING: no hg executable found
16:10:53 DEBUG: WARNING: No Git executable found. You must install Git in order to proceed!
16:10:53 DEBUG: WARNING: No Git executable found. You must install Git in order to proceed!
16:10:53 DEBUG: WARNING: no hg executable found
16:10:53 DEBUG: WARNING: No Git executable found. You must install Git in order to proceed!
16:10:53 DEBUG: WARNING: no hg executable found
16:10:53 DEBUG: WARNING: No Git executable found. You must install Git in order to proceed!
```

**Comment by dougxc** [comment]
Warnings should be fixed by https://github.com/graalvm/mx/commit/e6de4f81626759af3c2b7793f046c63c43c750ae
