### ISSUE TITLE
lack of .git directories results in: AttributeError: 'NoneType' object has no attribute 'parent'

### ISSUE THREAD

**Issue by christhalinger** [graalvm/mx#131]
At Twitter our CI system builds from a source bundle which doesn't include `.git` directories. This has already been an issue a couple times in the past and now again with version `5.86.0`:

```
Traceback (most recent call last):
  File "/Users/cthalinger/jvmci-0.24/mx/mx.py", line 15308, in <module>
    main()
  File "/Users/cthalinger/jvmci-0.24/mx/mx.py", line 15216, in main
    _init_primary_suite(PrimarySuite(primarySuiteMxDir, load=not vc_command))
  File "/Users/cthalinger/jvmci-0.24/mx/mx.py", line 7265, in __init__
    SourceSuite.__init__(self, mxDir, primary=True, load=load, importing_suite=None)
  File "/Users/cthalinger/jvmci-0.24/mx/mx.py", line 6878, in __init__
    self._init_imports()
  File "/Users/cthalinger/jvmci-0.24/mx/mx.py", line 6406, in _init_imports
    suite_import = SuiteImport.parse_specification(import_dict, context=self, importer_version=self.version(), dynamicImport=self.dynamicallyImported, importer_in_subdir=self.dir != self.vc_dir)
  File "/Users/cthalinger/jvmci-0.24/mx/mx.py", line 6888, in version
    return self.vc.parent(self.vc_dir, abortOnError=abortOnError)
AttributeError: 'NoneType' object has no attribute 'parent'
```

**Comment by christhalinger** [comment]
This patch fixes it:

```
diff --git a/mx.py b/mx.py
index 707e3d4..824c4b3 100755
--- a/mx.py
+++ b/mx.py
@@ -6885,6 +6885,8 @@ class SourceSuite(Suite):
         Return the current head changeset of this suite.
         """
         # we do not cache the version because it changes in development
+        if not self.vc:
+            return None
         return self.vc.parent(self.vc_dir, abortOnError=abortOnError)
 
     def isDirty(self, abortOnError=True):
```

but I don't know if that's the right fix.

**Comment by dougxc** [comment]
I can apply this fix if it works for you. However, until time is invested in making mx work without version controlled repos, you may run into further issues. Part of such an effort would include adding an mx gate test to ensure such usage doesn't regress. Such an exercise would start something like this:
```
wget https://github.com/graalvm/graal-core/archive/master.zip
unzip master.zip
cd truffle-master
mx gate
```

**Comment by christhalinger** [comment]
Yes, please integrate this fix.

**Comment by dougxc** [comment]
Done: https://github.com/graalvm/mx/commit/f6ad1d2cf6818350039b7441313ec14ac96c56a9
