### ISSUE TITLE
`mx gate` fails on unchanged master when using multiple drives

### ISSUE THREAD

**Issue by JornVernee** [graalvm/mx#152]
I've been fiddling around with a local copy of the mx repo and wanted to test my changes using `mx gate`, but I kept running into the same error.

Then I tried just running `mx gate` on the unchanged master branch and got the same error. The error is:

```
gate: 12 Jun 2018 19:06:39(+00:07) END:   IDEConfigCheck [0:00:00.409000]
Traceback (most recent call last):
  File "J:\Projects\graal\mx3\mx_gate.py", line 352, in gate
    _run_gate(cleanArgs, args, tasks)
  File "J:\Projects\graal\mx3\mx_gate.py", line 457, in _run_gate
    mx.command_function('ideinit')([])
  File "J:\Projects\graal\mx3\mx.py", line 15034, in ideinit
    intellijinit(args.remainder, refreshOnly=refreshOnly, doFsckProjects=False, mx_python_modules=args.pythonProjects)
  File "J:\Projects\graal\mx3\mx.py", line 14362, in intellijinit
    _intellij_suite(args, suite, declared_modules, referenced_modules, refreshOnly, mx_python_modules, generate_external_projects, java_modules and not suite.isBinarySuite(), suite != primary_suite())
  File "J:\Projects\graal\mx3\mx.py", line 14694, in _intellij_suite
    path = os.path.relpath(library.get_path(True), s.dir)
  File "J:\Python27\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive C:, start on drive J:
gate: 12 Jun 2018 19:06:39(+00:07) ABORT: Gate [0:00:07.875000]
path is on drive C:, start on drive J:
```

This looks like a Windows only problem, so I'll look into fixing it myself as well, but any suggestions are appreciated.

**Comment by JornVernee** [comment]
Looks like it's working when using the cygwin shell
