### ISSUE TITLE
TypeError: can only concatenate tuple (not "str") to tuple

### ISSUE THREAD

**Issue by fniephaus** [graalvm/mx#153]
When trying to build graal/tools, I'm getting the following error:

```
graal/tools (b76cd1450aa) $ mx build
JAVA_HOME:
EXTRA_JAVA_HOMES:
project org.graalvm.options was removed as JDK 1.8 is not available
project org.graalvm.polyglot was removed as JDK 1.8 is not available
project org.graalvm.word was removed as JDK 1.8 is not available
project org.graalvm.nativeimage was removed as JDK 1.8 is not available
project org.graalvm.collections was removed as JDK 1.8 is not available
Traceback (most recent call last):
  File "/Users/fniephaus/dev/graal/mx/mx.py", line 17697, in <module>
    main()
  File "/Users/fniephaus/dev/graal/mx/mx.py", line 17678, in main
    retcode = c(command_args)
  File "/Users/fniephaus/dev/graal/mx/mx.py", line 11570, in build
    log(reason)
  File "/Users/fniephaus/dev/graal/mx/mx.py", line 11097, in log
    print msg + "\n",
TypeError: can only concatenate tuple (not "str") to tuple
[1]    27515 exit 1     mx build
```

**Comment by fniephaus** [comment]
Working around this issue reveals the real problem:

```
Could not find a JDK
The following JDKs are available:
  /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
  /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
```

**Comment by dougxc** [comment]
Hi @fniephaus , thanks for the report. I'm pushing a fix for the TypeError failure now.

**Comment by dougxc** [comment]
Fixed in https://github.com/graalvm/mx/commit/f399c41edc06b5e7c4109b8f785303feb811c7b3.
