### ISSUE TITLE
JaCoCo Code Coverage broken in 5.187.0

### ISSUE THREAD

**Issue by fniephaus** [graalvm/mx#160]
https://github.com/graalvm/mx/commit/c0d2274455aac146a2b95817bd39934295cfd073 by @zapster has introduced changes that let coverage testing fail on our CI servers when mx `5.187.0` is used. Example error:
```
java.lang.instrument.IllegalClassFormatException: Error while instrumenting class MyClass.
	at org.jacoco.agent.rt.internal_8ff85ea.CoverageTransformer.transform(CoverageTransformer.java:93)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.oracle.mxtool.junit.MxJUnitRequest$Builder.resolveClass(MxJUnitRequest.java:72)
	at com.oracle.mxtool.junit.MxJUnitRequest$Builder.addTestSpec(MxJUnitRequest.java:97)
	at com.oracle.mxtool.junit.MxJUnitWrapper.main(MxJUnitWrapper.java:179)
Caused by: java.io.IOException: Error while instrumenting class MyClass.
	at org.jacoco.agent.rt.internal_8ff85ea.core.instr.Instrumenter.instrumentError(Instrumenter.java:166)
	at org.jacoco.agent.rt.internal_8ff85ea.core.instr.Instrumenter.instrument(Instrumenter.java:117)
	at org.jacoco.agent.rt.internal_8ff85ea.CoverageTransformer.transform(CoverageTransformer.java:91)
	... 31 more
Caused by: java.lang.IllegalStateException: Class MyClass is already instrumented.
	at org.jacoco.agent.rt.internal_8ff85ea.core.internal.instr.InstrSupport.assertNotInstrumented(InstrSupport.java:176)
	at org.jacoco.agent.rt.internal_8ff85ea.core.internal.instr.ClassInstrumenter.visitField(ClassInstrumenter.java:55)
	at org.jacoco.agent.rt.internal_8ff85ea.asm.ClassVisitor.visitField(ClassVisitor.java:272)
	at org.jacoco.agent.rt.internal_8ff85ea.asm.ClassReader.readField(ClassReader.java:783)
	at org.jacoco.agent.rt.internal_8ff85ea.asm.ClassReader.accept(ClassReader.java:704)
	at org.jacoco.agent.rt.internal_8ff85ea.asm.ClassReader.accept(ClassReader.java:521)
	at org.jacoco.agent.rt.internal_8ff85ea.core.instr.Instrumenter.instrument(Instrumenter.java:90)
	at org.jacoco.agent.rt.internal_8ff85ea.core.instr.Instrumenter.instrument(Instrumenter.java:114)
	... 32 more
```

**Comment by zapster** [comment]
Hi Fabio, hanks for your report!
Can you give a little bit more details, e.g., a command line which used to work but does no longer after the change so I can reproduce the issue locally?
More specifically, are you running with a `/compiler` import or not?

**Comment by fniephaus** [comment]
I'm afraid I don't have a command line for you to reproduce since our project is not public at this time. But yes, we are running it with a `/compiler` import. I googled the error which brings up different reasons...I haven't figured out yet which one applies here

**Comment by zapster** [comment]
I believe I've spotted the issue. The JaCoCo agent is attached twice, by mx and by the `/compiler` suite. So the error message is indeed quite accurate. :)
I'm preparing a fix.

**Comment by fniephaus** [comment]
Perfect, thanks!

**Comment by zapster** [comment]
Should be fixed with [5.188.1](https://github.com/graalvm/mx/releases/tag/5.188.1). Can you verify and close the issue if it is fixed?

PS: nice to see that someone cares about coverage. :)

**Comment by fniephaus** [comment]
Works like a charm, thanks!

PS: coverage is too important to not care about. ;)

**Comment by zapster** [comment]
Glad to hear that things are fine again and sorry for the inconvenience.

**Comment by fniephaus** [comment]
No problem! Things break sometimes when they are moving fast :)
