### ISSUE TITLE
Running mx gate on the mx suite throws an error on Windows

### ISSUE THREAD

**Issue by JornVernee** [graalvm/mx#165]
When running the `mx gate` command on the mx repo/suite I'm seeing the following error:

```
Traceback (most recent call last):
  File "J:\Projects\mx\mx_gate.py", line 411, in gate
    _run_gate(cleanArgs, args, tasks)
  File "J:\Projects\mx\mx_gate.py", line 518, in _run_gate
    mx.command_function('ideinit')([])
  File "J:\Projects\mx\mx_commands.py", line 132, in __call__
    return self.command_function(*args, **kwargs)
  File "J:\Projects\mx\mx.py", line 16194, in ideinit
    intellijinit(args.remainder, refreshOnly=refreshOnly, doFsckProjects=False, mx_python_modules=args.pythonProjects)
  File "J:\Projects\mx\mx.py", line 15373, in intellijinit
    sdks = intellij_read_sdks()
  File "J:\Projects\mx\mx.py", line 15426, in intellij_read_sdks
    xmlSdks.sort(key=verSort)
  File "J:\Projects\mx\mx.py", line 15424, in verSort
    return match.group(2) + (".a" if match.group(1) == "IntellijIC" else ".b")
AttributeError: 'NoneType' object has no attribute 'group'
```
The full log can be found here: https://gist.github.com/JornVernee/6b4d368d1ff241d40e5b750adab0ce82

**Comment by JornVernee** [comment]
I have a have a patch for this and some other minor errors that needed fixing to get `mx gate` passing, but I'm waiting for https://github.com/graalvm/mx/pull/164 and https://github.com/graalvm/mx/pull/167 to be merged before making a PR since I'm downstream from those.
