### ISSUE TITLE
Running the mx help command on the jdk/jdk .mx.graal suite throws an error on Windows

### ISSUE THREAD

**Issue by JornVernee** [graalvm/mx#166]
When running the `mx help` command on the graal suite included with the openjdk [1] I'm seeing the following error:

```
PS J:\cygwin64\home\Jorn\cygwin-projects\jdk\src\jdk.internal.vm.compiler> mx help
WARNING: project org.graalvm.compiler.microbenchmarks:
`isTestProject` attribute has been renamed to `testProject`
WARNING: project org.graalvm.compiler.virtual.bench:
`isTestProject` attribute has been renamed to `testProject`
Traceback (most recent call last):
  File "J:\Projects\mx\mx.py", line 18821, in <module>
    main()
  File "J:\Projects\mx\mx.py", line 18733, in main
    primary_suite().recursive_post_init()
  File "J:\Projects\mx\mx.py", line 8893, in recursive_post_init
    self._init_metadata()
  File "J:\Projects\mx\mx.py", line 8925, in _init_metadata
    self._load_metadata()
  File "J:\Projects\mx\mx.py", line 9164, in _load_metadata
    self._finish_load_projects()
  File "J:\Projects\mx\mx.py", line 9243, in _finish_load_projects
    with open(configFile) as fp:
  File "J:\Projects\mx\mx.py", line 13582, in open
    return __builtin__.open(name, mode=mode)
IOError: [Errno 22] invalid mode ('r') or filename: '\\\\?\\J:\\cygwin64\\home\\Jorn\\cygwin-projects\\jdk\\src\\jdk.internal.vm.compiler\\share/classes\\org.graalvm.compiler.core.match.processor\\src\\META-INF\\services\\javax.annotation.processing.Processor'
```

Please note that while the directory is located in the cygwin file system, I'm running this command in PowerShell.

[1] : http://hg.openjdk.java.net/jdk/jdk/file/4547f8303f2d/src/jdk.internal.vm.compiler

**Comment by JornVernee** [comment]
This seems to be caused by the path using a unix path separator `share/classes` if I change all those paths to `share\\classes` the error goes away.

I think paths coming from a suite should be 'sanitized' to use the right path separator, but I'm not sure where to do that.

**Comment by zakkak** [comment]
I have experienced the same issue.
Additionally, `wsloc` in `generate_eclipse_workingsets` in mx.py uses unix path separators breaking `mx eclipseinit` on windows.

**Comment by JornVernee** [comment]
Possible fix:

```
 mx.py | 1 +
 1 file changed, 1 insertion(+)

diff --git a/mx.py b/mx.py
index 9d7d452..ebac962 100755
--- a/mx.py
+++ b/mx.py
@@ -13615,6 +13615,7 @@ def _safe_path(path):
     https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath
     """
     if get_os() == 'windows':
+        path = path.replace("/", "\\")
         if isabs(path):
             if path.startswith('\\\\'):
                 if path[2:].startswith('?\\'):

```
