### ISSUE TITLE
mx build fails with "AssertionError"

### ISSUE THREAD

**Issue by slav9n4ik** [graalvm/mx#193]
When I try "mx build" in dir with ../graal/compiler, I see this error. What is wrong? 

```
Traceback (most recent call last):
  File "/home.../mx/mx.py", line 19174, in <module>
    main()
  File "/home.../mx/mx.py", line 19061, in main
    primary = _discover_suites(primarySuiteMxDir, load=should_load_suites)
  File "/home.../mx/mx.py", line 18873, in _discover_suites
    discovered_suite, is_clone = _find_suite_import(importing_suite, suite_import, load=False)
  File "/home.../mx/mx.py", line 18596, in _find_suite_import
    import_mx_dir = _find_or_clone()
  File "/home.../mx/mx.py", line 18564, in _find_or_clone
    _import_mx_dir = _find_suite_dir(search_mode)
  File "/home.../mx/mx.py", line 18535, in _find_suite_dir
    return _suitemodel.find_suite_dir(suite_import)
  File "/home.../mx/mx.py", line 8127, in find_suite_dir
    return self._search_dir(self._suiteRootDir, suite_import)
  File `"/home.../mx/mx.py",` line 8044, in _search_dir
    assert sd
AssertionError

```
**mx version** 
5.216.1

**graal branch** 
release/graal-vm/1.0

**java -version**
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**Comment by dougxc** [comment]
I'm having trouble reproducing this.

Can you please apply the patch below to mx and then attach the full output of `mx build` (at least the initial lines showing the values of `JAVA_HOME` and `EXTRA_JAVA_HOMES`):
```
diff --git a/mx.py b/mx.py
index d421ce8..1d6e720 100755
--- a/mx.py
+++ b/mx.py
@@ -8041,7 +8041,7 @@ class SuiteModel:
     def _search_dir(self, searchDir, suite_import):
         if suite_import.suite_dir:
             sd = _is_suite_dir(suite_import.suite_dir, _mxDirName(suite_import.name))
-            assert sd
+            assert sd, '{} {}'.format(suite_import.suite_dir, _mxDirName(suite_import.name))
             return sd

         if not exists(searchDir):
```

**Comment by slav9n4ik** [comment]
`~/Documents/graalProj/graal/compiler$ mx build`
Full output:
```
Traceback (most recent call last):
  File "/home/viacheslav/Documents/graalProj/mx/mx.py", line 19174, in <module>
    main()
  File "/home/viacheslav/Documents/graalProj/mx/mx.py", line 19061, in main
    primary = _discover_suites(primarySuiteMxDir, load=should_load_suites)
  File "/home/viacheslav/Documents/graalProj/mx/mx.py", line 18873, in _discover_suites
    discovered_suite, is_clone = _find_suite_import(importing_suite, suite_import, load=False)
  File "/home/viacheslav/Documents/graalProj/mx/mx.py", line 18596, in _find_suite_import
    import_mx_dir = _find_or_clone()
  File "/home/viacheslav/Documents/graalProj/mx/mx.py", line 18564, in _find_or_clone
    _import_mx_dir = _find_suite_dir(search_mode)
  File "/home/viacheslav/Documents/graalProj/mx/mx.py", line 18535, in _find_suite_dir
    return _suitemodel.find_suite_dir(suite_import)
  File "/home/viacheslav/Documents/graalProj/mx/mx.py", line 8127, in find_suite_dir
    return self._search_dir(self._suiteRootDir, suite_import)
  File "/home/viacheslav/Documents/graalProj/mx/mx.py", line 8044, in _search_dir
    assert sd, '{} {}'.format(suite_import.suite_dir, _mxDirName(suite_import.name))
AssertionError: /home/viacheslav/Documents/graalProj/truffle mx.truffle
```
So, I copied all graal project from :
> ~/Documents/graalProj/graal 

to the same directory with mx:
> ~/Documents/graalProj/

now it's work fine, thanks!

**Comment by dougxc** [comment]
Glad you could resolve the problem.
