### ISSUE TITLE
mx Assertion Error

### ISSUE THREAD

**Issue by Yuhala** [graalvm/mx#250]
I am trying to build the base GraalVM CE image following the instructions in the github readme, using the latest version of mx. However mx keeps producing the error below: 

```
Traceback (most recent call last):
  File "/home/petman/projects/graal-truffle-root/sgx-truffle/mx/mx.py", line 17945, in <module>
    main()
  File "/home/petman/projects/graal-truffle-root/sgx-truffle/mx/mx.py", line 17839, in main
    primary = _discover_suites(primarySuiteMxDir, load=should_load_suites)
  File "/home/petman/projects/graal-truffle-root/sgx-truffle/mx/mx.py", line 17641, in _discover_suites
    discovered_suite, is_clone = _find_suite_import(importing_suite, suite_import, load=False)
  File "/home/petman/projects/graal-truffle-root/sgx-truffle/mx/mx.py", line 17377, in _find_suite_import
    import_mx_dir = _find_or_clone()
  File "/home/petman/projects/graal-truffle-root/sgx-truffle/mx/mx.py", line 17345, in _find_or_clone
    _import_mx_dir = _find_suite_dir(search_mode)
  File "/home/petman/projects/graal-truffle-root/sgx-truffle/mx/mx.py", line 17316, in _find_suite_dir
    return _suitemodel.find_suite_dir(suite_import)
  File "/home/petman/projects/graal-truffle-root/sgx-truffle/mx/mx.py", line 7163, in find_suite_dir
    return self._search_dir(self._suiteRootDir, suite_import)
  File "/home/petman/projects/graal-truffle-root/sgx-truffle/mx/mx.py", line 7079, in _search_dir
    assert sd
AssertionError
```

This happens each time I run the mx command inside a GraalVM suite folder i.e vm, truffle, substratevm etc. I have added mx to the PATH and the JAVA_HOME points to openjdk1.8.0_302-jvmci-20.3-b23. The root graal folder(containing all suites) is located in: /home/petman/projects/graal-truffle-root/sgx-truffle

**Comment by fniephaus** [comment]
You're using an outdated JVMCI-enabled JDK. Note that JDK8 is no longer supported. Please try again with the latest labs-openjdk-11 from: https://github.com/graalvm/labs-openjdk-11

**Comment by Yuhala** [comment]
I have tested with `labsjdk-ce-11.0.14-jvmci-20.3-b26` but I have the same error.

**Comment by fniephaus** [comment]
20.3 is still too old if you want to build master. Currently, we are at 22.0 or even 22.1:

https://github.com/oracle/graal/blob/a46779dea4fb58057529d6a1506630a0a1d8067f/common.json#L11

**Comment by Yuhala** [comment]
Thanks, it works now with 22.0.

**Comment by fniephaus** [comment]
Glad to hear! Whenever "mx build" fails for me, I usually run "mx update" and if that doesn't fix it, I pull the latest LabsJDK and retry.
