### ISSUE TITLE
Canonicalization Check fails (makes it impossible to depend JavaProject on NativeProject)

### ISSUE THREAD

**Issue by olpaw** [graalvm/mx#90]
The suite.py constellation below causes:
```
Traceback (most recent call last):
  File "/home/pwoegere/labs/xxx/mx_olpaw/mx_gate.py", line 267, in gate
    if mx.command_function('canonicalizeprojects')([]) != 0:
  File "/home/pwoegere/labs/xxx/mx_olpaw/mx.py", line 8931, in canonicalizeprojects
    if pkg in dep.extended_java_packages():
AttributeError: 'NativeProject' object has no attribute 'extended_java_packages'
gate: 17 Mar 2016 15:07:00: ABORT: Gate [0:00:11.244213] [disk (free/total): 305.7GB/430.1GB]
'NativeProject' object has no attribute 'extended_java_packages'
```
I think it should be possible for a JavaProject to depend on a NativeProject:
```
    "com.oracle.xxx.core.dis" : {
      "subDir" : "xxx",
      "sourceDirs" : ["src"],
      "dependencies" : [
        "com.oracle.xxx.core",
        "com.oracle.xxx.core.dis.native",
      ],
      "annotationProcessors" : [
        "graal-core:GRAAL_NODEINFO_PROCESSOR",
        "graal-core:GRAAL_REPLACEMENTS_VERIFIER",
        "graal-core:GRAAL_OPTIONS_PROCESSOR",
        "truffle:TRUFFLE_DSL_PROCESSOR",
      ],
      "javaCompliance" : "1.8",
      "checkstyle" : "com.oracle.xxx.truffle",
      "workingSets" : "XXX",
      "findbugs" : "false",
    },

    "com.oracle.xxx.core.dis.native" : {
      "native" : True,
      "subDir" : "xxx",
      "dependencies" : ["DISTORM"],
      "output" : "clibraries",
      "results" : [
        "libdistorm3.a",
        "include/distorm.h",
        "include/mnemonics.h",
      ]
    },
```
Here `com.oracle.xxx.core.dis` depends on `com.oracle.xxx.core.dis.native`. Unfortunately using the definition above results in the error shown before.

**Comment by dougxc** [comment]
Can we close this issue @olpaw ?
